
apiVersion: apps/v1
kind: Deployment

metadata:
  name: my-api-deployment
  namespace: kouti-flask-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
      - name: my-api-container
        image: kouti/flask:latest  
        ports:
        - containerPort: 5000 