apiVersion: v1
kind: Service
metadata:
  name: my-api-service
spec:
  selector:
    app: my-api
  ports:
  - protocol: TCP
    port: 80  # External port to expose
    targetPort: 5000  # Port exposed by the container