name: CI/CD Pipeline for Flask App Deployment with Security

on:
  push:
    branches:
      - main  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 3: Set Kubernetes context (Generic Kubernetes Cluster)
      - name: Set Kubernetes context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}  # Ensure this is added as a GitHub Secret


      # Step 4: Create namespace if it doesn't exist
      - name: Create Namespace
        run: |
          kubectl create namespace kouti-flask-app-namespace --validate=false

      # Step 5: Verify Kubernetes cluster connectivity
      - name: Verify cluster connectivity
        run: kubectl get nodes --namespace kouti-flask-app-namespace

      # Step 6: Deploy the app to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./deployment.yaml --namespace kouti-flask-app-namespace 
          kubectl apply -f ./service.yaml --namespace kouti-flask-app-namespace

      # Optional Step: Verify that the app was deployed successfully
      - name: Check Deployment Status
        run: kubectl rollout status deployment/kouti-flask-app-deployment --namespace kouti-flask-app-namespace
